/** Alle Texte der Meta-Bildschirme (Spieler sehen Englisch). */
export const fmt = (n: number): string => n.toLocaleString('en-US');

export const S = {
  title: 'DUSKWARDENS',
  resetNotice: {
    title: 'Fresh start',
    text: 'Duskwardens has been rebuilt from scratch. Your old progress was reset.',
    ok: 'OK',
  },
  home: {
    level: 'Level',
    xp: 'XP',
    maxLevel: 'Max level',
    play: 'Play',
    towers: 'Towers',
    knowledge: 'Knowledge',
    settings: 'Settings',
    points: (n: number): string => `${n} point${n === 1 ? '' : 's'} to spend`,
    pickDifficulty: 'Difficulty',
    lockedAt: (n: number): string => `Level ${n}`,
    best: (r: number): string => `Best: round ${r}`,
    noBest: 'Not played yet',
    lineup: 'Your wardens',
    heroTag: 'Hero',
    medalsDone: 'All medals earned',
    readyTower: 'Tower upgrades ready',
    difficulty: { easy: 'Easy', medium: 'Medium', hard: 'Hard' },
    diffText: {
      easy: 'More lives, cheaper towers.',
      medium: 'The standard way to play.',
      hard: 'Pricey towers, faster foes.',
    },
  },
  result: {
    victory: 'Victory',
    defeat: 'Defeat',
    left: 'Match ended',
    round: (r: number, max: number): string => `Round ${r} of ${max}`,
    xpGained: (n: number): string => `+${fmt(n)} XP`,
    levelUp: 'Level up',
    newLevel: (n: number): string => `Level ${n}`,
    unlocked: 'Unlocked',
    point: '+1 Knowledge Point',
    points: (n: number): string => `+${n} Knowledge Point${n === 1 ? '' : 's'}`,
    newMedal: (d: string): string => `New ${d} medal`,
    newBest: 'New best',
    towerXp: 'Tower XP',
    ready: 'Ready to unlock',
    nextAt: (cost: number): string => `next unlock: ${cost}`,
    allDone: 'All tiers unlocked',
    again: 'Again',
    home: 'Home',
    toTower: 'Unlock upgrades',
    skip: 'Skip',
    duplicate: 'This match was already counted.',
    noTowerXp: 'No tower got XP this match.',
  },
  knowledge: {
    title: 'Knowledge',
    points: 'Points',
    reset: 'Reset tree',
    resetHint: 'Refunds every point. Free.',
    cost: (n: number): string => `${n} point${n === 1 ? '' : 's'}`,
    learned: 'Learned',
    needs: (name: string): string => `Needs ${name} first`,
    needsOne: (names: string): string => `Needs one of: ${names}`,
    noPoints: 'Not enough points',
    branch: { economy: 'Economy', towers: 'Towers', wardens: 'Wardens' },
    tip: 'Each level up earns one point.',
  },
  towers: {
    title: 'Towers',
    xp: 'Tower XP',
    unlock: 'Unlock',
    unlocked: 'Unlocked',
    needXp: (n: number): string => `Needs ${n} XP`,
    lockedTower: (n: number): string => `Reach level ${n} to use this tower.`,
    unlockedAll: 'Developer mode: everything is unlocked.',
    price: (n: number): string => `${fmt(n)} gold`,
    best: 'Your best build',
    tier: (n: number): string => `Tier ${n}`,
    preview: 'Preview',
    lockedBadge: (n: number): string => `Level ${n}`,
    howto: 'Tower XP comes from cracked layers and bought upgrades. Spend it here.',
    paths: {
      ranger: ['Volley', 'Rapid', 'Eagle Eye'],
      bombardier: ['Bigger Blasts', 'Clusters', 'Concussion'],
      frostcaller: ['Permafrost', 'Shatter', 'Storm'],
    } as Record<string, string[]>,
  },
  settings: {
    title: 'Settings',
    volume: 'Volume',
    dev: 'Developer: unlock everything',
    devHint: 'Every tower and every upgrade is free to use. Progress still counts.',
    save: 'Save data',
    export: 'Export',
    import: 'Import',
    exportDone: 'Save exported.',
    importDone: 'Save imported.',
    importFail: (m: string): string => `Import failed: ${m}`,
    wipe: 'Delete profile',
    wipeHint: 'Removes all levels, XP, medals and knowledge.',
    wipeAsk: 'Delete everything?',
    wipeText: 'All levels, tower XP, knowledge and medals are removed for good. Export first if you want a copy.',
    wipeYes: 'Delete',
    wipeNo: 'Keep',
    stored: { indexeddb: 'Stored in this browser (IndexedDB).', localstorage: 'Stored in this browser (local storage).', memory: 'Not stored: only kept until you close the tab.' } as Record<string, string>,
    stats: (p: number, w: number): string => `${p} matches played, ${w} won`,
  },
  back: 'Back',
  close: 'Close',
};

